# Generated by Django 2.2.7 on 2019-11-30 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191129_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='neighbourhood.Neighbourhood'),
        ),
    ]
